name: 'Build JSON schemas'
description: 'Build, validate and prettify JSON schemas'
inputs:
  raw:
    description: "Path to the input directory containing the raw schemas"
    required: false
    default: "raw"
  resolved:
    description: "Path to the output directory containing the resolved schemas"
    required: false
    default: "resolved"
  docs:
    description: "Path to the output directory containing the human-readable schemas"
    required: false
    default: "public"
  title:
    description: "Title for the landing page"
    required: false
    default: "Schema overview"
  tarball:
    description: "Path to an output tarball containing all resolved schemas."
    required: false
    default: ""
runs:
  using: 'docker'
  image: 'docker://ghcr.io/artifactdb/build-schemas-action/builder:master'
  args:
    - ${{ inputs.raw }}
    - ${{ inputs.resolved }}
    - ${{ inputs.docs }}
    - ${{ inputs.title }}
    - ${{ inputs.tarball }}
